septimo commit

diff --git a/.github/workflows/deploy-ec2.yml b/.github/workflows/deploy-ec2.yml
--- a/.github/workflows/deploy-ec2.yml
+++ b/.github/workflows/deploy-ec2.yml
@@ -13,16 +13,23 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Verify index.html exists
+        run: |
+          if [ ! -f ./index.html ]; then
+            echo "Error: index.html no encontrado en el repositorio."
+            exit 1
+          fi
+
       - name: Copy HTML to EC2
         uses: appleboy/scp-action@v0.1.3
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
-          source: "./index.html"
+          source: "index.html"
           target: "/tmp/"
 
-      - name: Move HTML to target directory
+      - name: Move HTML to target directory and restart Nginx
         uses: appleboy/ssh-action@v0.1.5
         with:
           host: ${{ secrets.EC2_HOST }}
